### PR TITLE
Remove /say command

### PR DESCRIPTION
**Pull request by Scrumplex**
Let's just use the one from Lily instead.

### CODE REVIEW

**Comment by ryanccn** [comment]
Isn't the point of the command to say something via the bot? If that's the case different bots should have their own say commands.

**Comment by Scrumplex** [comment]
I mean instead of this I wouldn't mind having some kind of log to see who sent the message. Lily logs this, Refraction doesn't.

**Comment by ryanccn** [comment]
Make a PR to add that then :trollface:

**Comment by IThundxr** [comment]
Mods can't use it anyway so Approved!

**Review by IThundxr — APPROVED** [review]
LGTM!

**Pull request closed without merging**
