### PR TITLE
Mid-fall Nix and CI cleaning

### PR DESCRIPTION
**Pull request by getchoo**
I nitpicked my own Nix
Call it nixpicking

~~We've also had Docker images failing to build a while because of rust-overlay being bumped to 1.80.0 and one of our deps not working for it yet it seems :/~~ FIXED!

We should change the required checks to the Clippy scan, "CI Release Gate", and "Docker Release" in the repo as to avoid things breaking again

### CODE REVIEW

**Review by Scrumplex — COMMENTED** [review]
Why don't we build this using Nix anymore in CI? That is the main way I deploy refraction

**Comment by getchoo** [comment]
> Why don't we build this using Nix anymore in CI?

The main package has been added to `checks` with `nix-fast-build` building it now

**Comment by Scrumplex** [comment]
I don't quite understand the usefulness of building on all three platforms supported by GH Actions, though. Seems quite wasteful for next to no gain.

**Comment by getchoo** [comment]
I'm not a big fan of it either, but i've caught myself accidentally adding os-specific stuff from time to time (looking at you tokio). I don't know how else we can continuously make sure contributors are able to build locally otherwise

The only real option I see is dropping the regular rust linux build and just using Nix instead?

**Comment by getchoo** [comment]
Only Linux and Windows are built now, as there shouldn't be anything *Linux* specific here, only Unix. We don't really need to worry about it in the Nix package either

**Review by Scrumplex — APPROVED** [review]

**Pull request merged**
